services:
  app:
    environment:
      PORT: 3000
      ENCRYPTION_HASH_ROUNDS: 10
      MONGODB_URI: mongodb://root:example@mongo:27017/admin
    ports:
      - 3000:3000
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false